// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tencent.client.common.protos;

public interface VoidReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoidReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 itemId = 1;</code>
   */
  long getItemId();
}
