// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tencent.client.common.protos;

public interface VoidRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoidResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
