// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public final class ClientMasterProto {
  private ClientMasterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterWorkerReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterWorkerReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterWorkerResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterWorkerResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterWorkerResp_ConfEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterWorkerResp_ConfEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterTaskReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterTaskReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterTaskResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterTaskResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterTaskResp_ClockEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterTaskResp_ClockEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_SetAngelLocationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_SetAngelLocationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetAngelLocationResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetAngelLocationResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_HeartBeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_HeartBeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_HeartBeatResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_HeartBeatResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_ClockReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_ClockReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_ClockResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_ClockResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_ClockResp_ClockMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_ClockResp_ClockMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetClockMapReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetClockMapReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetClockMapResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetClockMapResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetClockMapResp_ClockMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetClockMapResp_ClockMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetGlobalBatchResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetGlobalBatchResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023client_master.proto\022\014ClientMaster\032\014com" +
      "mon.proto\"/\n\021RegisterWorkerReq\022\014\n\004host\030\001" +
      " \001(\t\022\014\n\004port\030\002 \001(\005\"\345\001\n\022RegisterWorkerRes" +
      "p\022\013\n\003ret\030\001 \001(\005\022\016\n\006workId\030\002 \001(\003\022\017\n\007isChie" +
      "f\030\003 \001(\010\022\037\n\nasyncModel\030\005 \001(\0162\013.AsyncModel" +
      "\0228\n\004conf\030\006 \003(\0132*.ClientMaster.RegisterWo" +
      "rkerResp.ConfEntry\022\031\n\021heartBeatInterval\030" +
      "\007 \001(\005\032+\n\tConfEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"4\n\017RegisterTaskReq\022\016\n\006workId\030" +
      "\002 \001(\003\022\021\n\ttimestamp\030\003 \001(\003\"\233\001\n\020RegisterTas" +
      "kResp\022\016\n\006taskId\030\002 \001(\003\022\017\n\007numTask\030\004 \001(\005\0228" +
      "\n\005clock\030\003 \003(\0132).ClientMaster.RegisterTas" +
      "kResp.ClockEntry\032,\n\nClockEntry\022\013\n\003key\030\001 " +
      "\001(\003\022\r\n\005value\030\002 \001(\005:\0028\001\"A\n\023SetAngelLocati" +
      "onReq\022\016\n\006workId\030\001 \001(\003\022\014\n\004host\030\002 \001(\t\022\014\n\004p" +
      "ort\030\003 \001(\005\"?\n\024GetAngelLocationResp\022\014\n\004hos" +
      "t\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\013\n\003msg\030\004 \001(\t\"\036\n\014He" +
      "artBeatReq\022\016\n\006workId\030\001 \001(\003\"3\n\rHeartBeatR" +
      "esp\022\"\n\003cmd\030\003 \001(\0162\025.ClientMaster.Command\"" +
      "<\n\010ClockReq\022\016\n\006taskId\030\001 \001(\003\022\r\n\005clock\030\002 \001" +
      "(\005\022\021\n\tbatchSize\030\003 \001(\005\"\205\001\n\tClockResp\022\016\n\006t" +
      "askId\030\001 \001(\003\0227\n\010clockMap\030\002 \003(\0132%.ClientMa" +
      "ster.ClockResp.ClockMapEntry\032/\n\rClockMap" +
      "Entry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\005:\0028\001\" \n" +
      "\016GetClockMapReq\022\016\n\006taskId\030\001 \001(\003\"\221\001\n\017GetC" +
      "lockMapResp\022\016\n\006taskId\030\001 \001(\003\022=\n\010clockMap\030" +
      "\002 \003(\0132+.ClientMaster.GetClockMapResp.Clo" +
      "ckMapEntry\032/\n\rClockMapEntry\022\013\n\003key\030\001 \001(\003" +
      "\022\r\n\005value\030\002 \001(\005:\0028\001\"\'\n\022GetGlobalBatchRes" +
      "p\022\021\n\tbatchSize\030\001 \001(\005*F\n\007Command\022\r\n\tSTOPA" +
      "NGEL\020\000\022\017\n\013STOPPSAGENT\020\001\022\016\n\nSTOPWORKER\020\002\022" +
      "\013\n\007NOTHING\020\0032\210\005\n\021AngelCleintMaster\022U\n\016Re" +
      "gisterWorker\022\037.ClientMaster.RegisterWork" +
      "erReq\032 .ClientMaster.RegisterWorkerResp\"" +
      "\000\022O\n\014RegisterTask\022\035.ClientMaster.Registe" +
      "rTaskReq\032\036.ClientMaster.RegisterTaskResp" +
      "\"\000\022B\n\020SetAngelLocation\022!.ClientMaster.Se" +
      "tAngelLocationReq\032\t.VoidResp\"\000\022B\n\020GetAng" +
      "elLocation\022\010.VoidReq\032\".ClientMaster.GetA" +
      "ngelLocationResp\"\000\022F\n\tHeartBeat\022\032.Client" +
      "Master.HeartBeatReq\032\033.ClientMaster.Heart" +
      "BeatResp\"\000\022:\n\005Clock\022\026.ClientMaster.Clock" +
      "Req\032\027.ClientMaster.ClockResp\"\000\022L\n\013GetClo" +
      "ckMap\022\034.ClientMaster.GetClockMapReq\032\035.Cl" +
      "ientMaster.GetClockMapResp\"\000\022B\n\022GetGloba" +
      "lBatchSize\022\010.VoidReq\032 .ClientMaster.GetG" +
      "lobalBatchResp\"\000\022-\n\014CompleteTask\022\020.Compl" +
      "eteTaskReq\032\t.VoidResp\"\000B:\n com.tencent.c" +
      "lient.master.protosB\021ClientMasterProtoP\001" +
      "\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.client.common.protos.MWComProto.getDescriptor(),
        }, assigner);
    internal_static_ClientMaster_RegisterWorkerReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientMaster_RegisterWorkerReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterWorkerReq_descriptor,
        new java.lang.String[] { "Host", "Port", });
    internal_static_ClientMaster_RegisterWorkerResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientMaster_RegisterWorkerResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterWorkerResp_descriptor,
        new java.lang.String[] { "Ret", "WorkId", "IsChief", "AsyncModel", "Conf", "HeartBeatInterval", });
    internal_static_ClientMaster_RegisterWorkerResp_ConfEntry_descriptor =
      internal_static_ClientMaster_RegisterWorkerResp_descriptor.getNestedTypes().get(0);
    internal_static_ClientMaster_RegisterWorkerResp_ConfEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterWorkerResp_ConfEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ClientMaster_RegisterTaskReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientMaster_RegisterTaskReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterTaskReq_descriptor,
        new java.lang.String[] { "WorkId", "Timestamp", });
    internal_static_ClientMaster_RegisterTaskResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClientMaster_RegisterTaskResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterTaskResp_descriptor,
        new java.lang.String[] { "TaskId", "NumTask", "Clock", });
    internal_static_ClientMaster_RegisterTaskResp_ClockEntry_descriptor =
      internal_static_ClientMaster_RegisterTaskResp_descriptor.getNestedTypes().get(0);
    internal_static_ClientMaster_RegisterTaskResp_ClockEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterTaskResp_ClockEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ClientMaster_SetAngelLocationReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ClientMaster_SetAngelLocationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_SetAngelLocationReq_descriptor,
        new java.lang.String[] { "WorkId", "Host", "Port", });
    internal_static_ClientMaster_GetAngelLocationResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ClientMaster_GetAngelLocationResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetAngelLocationResp_descriptor,
        new java.lang.String[] { "Host", "Port", "Msg", });
    internal_static_ClientMaster_HeartBeatReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ClientMaster_HeartBeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_HeartBeatReq_descriptor,
        new java.lang.String[] { "WorkId", });
    internal_static_ClientMaster_HeartBeatResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ClientMaster_HeartBeatResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_HeartBeatResp_descriptor,
        new java.lang.String[] { "Cmd", });
    internal_static_ClientMaster_ClockReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ClientMaster_ClockReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_ClockReq_descriptor,
        new java.lang.String[] { "TaskId", "Clock", "BatchSize", });
    internal_static_ClientMaster_ClockResp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ClientMaster_ClockResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_ClockResp_descriptor,
        new java.lang.String[] { "TaskId", "ClockMap", });
    internal_static_ClientMaster_ClockResp_ClockMapEntry_descriptor =
      internal_static_ClientMaster_ClockResp_descriptor.getNestedTypes().get(0);
    internal_static_ClientMaster_ClockResp_ClockMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_ClockResp_ClockMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ClientMaster_GetClockMapReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ClientMaster_GetClockMapReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetClockMapReq_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_ClientMaster_GetClockMapResp_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ClientMaster_GetClockMapResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetClockMapResp_descriptor,
        new java.lang.String[] { "TaskId", "ClockMap", });
    internal_static_ClientMaster_GetClockMapResp_ClockMapEntry_descriptor =
      internal_static_ClientMaster_GetClockMapResp_descriptor.getNestedTypes().get(0);
    internal_static_ClientMaster_GetClockMapResp_ClockMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetClockMapResp_ClockMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ClientMaster_GetGlobalBatchResp_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ClientMaster_GetGlobalBatchResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetGlobalBatchResp_descriptor,
        new java.lang.String[] { "BatchSize", });
    com.tencent.client.common.protos.MWComProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
