// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public final class ClientMasterProto {
  private ClientMasterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_RegisterResp_ConfEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_RegisterResp_ConfEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_SetAngelLocationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_SetAngelLocationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_SetAngelLocationResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_SetAngelLocationResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetAngelLocationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetAngelLocationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_GetAngelLocationResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_GetAngelLocationResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_HeartBeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_HeartBeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_HeartBeatResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_HeartBeatResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_SyncReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_SyncReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMaster_SyncResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMaster_SyncResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023client_master.proto\022\014ClientMaster\032\014com" +
      "mon.proto\")\n\013RegisterReq\022\014\n\004host\030\001 \001(\t\022\014" +
      "\n\004port\030\002 \001(\005\"\345\001\n\014RegisterResp\022\024\n\003ret\030\001 \001" +
      "(\0162\007.Status\022\016\n\006workId\030\002 \001(\003\022\017\n\007isChief\030\003" +
      " \001(\010\022\017\n\007numTask\030\004 \001(\005\022\037\n\nasyncModel\030\005 \001(" +
      "\0162\013.AsyncModel\0222\n\004conf\0308 \003(\0132$.ClientMas" +
      "ter.RegisterResp.ConfEntry\022\013\n\003msg\030\006 \001(\t\032" +
      "+\n\tConfEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"A\n\023SetAngelLocationReq\022\016\n\006workId\030\001 " +
      "\001(\003\022\014\n\004host\030\002 \001(\t\022\014\n\004post\030\003 \001(\005\"9\n\024SetAn" +
      "gelLocationResp\022\024\n\003ret\030\001 \001(\0162\007.Status\022\013\n" +
      "\003msg\030\002 \001(\t\"%\n\023GetAngelLocationReq\022\016\n\006wor" +
      "kId\030\001 \001(\003\"U\n\024GetAngelLocationResp\022\024\n\003ret" +
      "\030\001 \001(\0162\007.Status\022\014\n\004host\030\002 \001(\t\022\014\n\004post\030\003 " +
      "\001(\005\022\013\n\003msg\030\004 \001(\t\"2\n\014HeartBeatReq\022\016\n\006work" +
      "Id\030\001 \001(\003\022\022\n\ntimestamps\030\002 \001(\003\"V\n\rHeartBea" +
      "tResp\022\024\n\003ret\030\001 \001(\0162\007.Status\022\013\n\003msg\030\002 \001(\t" +
      "\022\"\n\003cmd\030\003 \001(\0162\025.ClientMaster.Command\"(\n\007" +
      "SyncReq\022\016\n\006workId\030\001 \001(\003\022\r\n\005clock\030\002 \001(\005\"-" +
      "\n\010SyncResp\022\024\n\003ret\030\001 \001(\0162\007.Status\022\013\n\003msg\030" +
      "\002 \001(\t*9\n\007Command\022\r\n\tSTOPANGEL\020\000\022\017\n\013STOPP" +
      "SAGENT\020\001\022\016\n\nSTOPWORKER\020\0022\223\003\n\021AngelCleint" +
      "Master\022C\n\010Register\022\031.ClientMaster.Regist" +
      "erReq\032\032.ClientMaster.RegisterResp\"\000\022[\n\020S" +
      "etAngelLocation\022!.ClientMaster.SetAngelL" +
      "ocationReq\032\".ClientMaster.SetAngelLocati" +
      "onResp\"\000\022[\n\020GetAngelLocation\022!.ClientMas" +
      "ter.GetAngelLocationReq\032\".ClientMaster.G" +
      "etAngelLocationResp\"\000\022F\n\tHeartBeat\022\032.Cli" +
      "entMaster.HeartBeatReq\032\033.ClientMaster.He" +
      "artBeatResp\"\000\0227\n\004Sync\022\025.ClientMaster.Syn" +
      "cReq\032\026.ClientMaster.SyncResp\"\000B:\n com.te" +
      "ncent.client.master.protosB\021ClientMaster" +
      "ProtoP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.client.common.protos.MWComProto.getDescriptor(),
        }, assigner);
    internal_static_ClientMaster_RegisterReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientMaster_RegisterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterReq_descriptor,
        new java.lang.String[] { "Host", "Port", });
    internal_static_ClientMaster_RegisterResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientMaster_RegisterResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterResp_descriptor,
        new java.lang.String[] { "Ret", "WorkId", "IsChief", "NumTask", "AsyncModel", "Conf", "Msg", });
    internal_static_ClientMaster_RegisterResp_ConfEntry_descriptor =
      internal_static_ClientMaster_RegisterResp_descriptor.getNestedTypes().get(0);
    internal_static_ClientMaster_RegisterResp_ConfEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_RegisterResp_ConfEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ClientMaster_SetAngelLocationReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientMaster_SetAngelLocationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_SetAngelLocationReq_descriptor,
        new java.lang.String[] { "WorkId", "Host", "Post", });
    internal_static_ClientMaster_SetAngelLocationResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClientMaster_SetAngelLocationResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_SetAngelLocationResp_descriptor,
        new java.lang.String[] { "Ret", "Msg", });
    internal_static_ClientMaster_GetAngelLocationReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ClientMaster_GetAngelLocationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetAngelLocationReq_descriptor,
        new java.lang.String[] { "WorkId", });
    internal_static_ClientMaster_GetAngelLocationResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ClientMaster_GetAngelLocationResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_GetAngelLocationResp_descriptor,
        new java.lang.String[] { "Ret", "Host", "Post", "Msg", });
    internal_static_ClientMaster_HeartBeatReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ClientMaster_HeartBeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_HeartBeatReq_descriptor,
        new java.lang.String[] { "WorkId", "Timestamps", });
    internal_static_ClientMaster_HeartBeatResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ClientMaster_HeartBeatResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_HeartBeatResp_descriptor,
        new java.lang.String[] { "Ret", "Msg", "Cmd", });
    internal_static_ClientMaster_SyncReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ClientMaster_SyncReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_SyncReq_descriptor,
        new java.lang.String[] { "WorkId", "Clock", });
    internal_static_ClientMaster_SyncResp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ClientMaster_SyncResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMaster_SyncResp_descriptor,
        new java.lang.String[] { "Ret", "Msg", });
    com.tencent.client.common.protos.MWComProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
