// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface GetAngelLocationReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.GetAngelLocationReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 workId = 1;</code>
   */
  long getWorkId();
}
