// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface GetClockMapRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.GetClockMapResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 taskId = 1;</code>
   */
  long getTaskId();

  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */
  int getClockMapCount();
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */
  boolean containsClockMap(
      long key);
  /**
   * Use {@link #getClockMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Integer>
  getClockMap();
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Integer>
  getClockMapMap();
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */

  int getClockMapOrDefault(
      long key,
      int defaultValue);
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */

  int getClockMapOrThrow(
      long key);
}
