// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

/**
 * Protobuf type {@code ClientMaster.GetClockMapResp}
 */
public  final class GetClockMapResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientMaster.GetClockMapResp)
    GetClockMapRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetClockMapResp.newBuilder() to construct.
  private GetClockMapResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetClockMapResp() {
    taskId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetClockMapResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            taskId_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              clockMap_ = com.google.protobuf.MapField.newMapField(
                  ClockMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.Integer>
            clockMap__ = input.readMessage(
                ClockMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            clockMap_.getMutableMap().put(
                clockMap__.getKey(), clockMap__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_GetClockMapResp_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetClockMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_GetClockMapResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tencent.client.master.protos.GetClockMapResp.class, com.tencent.client.master.protos.GetClockMapResp.Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private long taskId_;
  /**
   * <code>int64 taskId = 1;</code>
   */
  public long getTaskId() {
    return taskId_;
  }

  public static final int CLOCKMAP_FIELD_NUMBER = 2;
  private static final class ClockMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, java.lang.Integer>newDefaultInstance(
                com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_GetClockMapResp_ClockMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Long, java.lang.Integer> clockMap_;
  private com.google.protobuf.MapField<java.lang.Long, java.lang.Integer>
  internalGetClockMap() {
    if (clockMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ClockMapDefaultEntryHolder.defaultEntry);
    }
    return clockMap_;
  }

  public int getClockMapCount() {
    return internalGetClockMap().getMap().size();
  }
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */

  public boolean containsClockMap(
      long key) {
    
    return internalGetClockMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getClockMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, java.lang.Integer> getClockMap() {
    return getClockMapMap();
  }
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */

  public java.util.Map<java.lang.Long, java.lang.Integer> getClockMapMap() {
    return internalGetClockMap().getMap();
  }
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */

  public int getClockMapOrDefault(
      long key,
      int defaultValue) {
    
    java.util.Map<java.lang.Long, java.lang.Integer> map =
        internalGetClockMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
   */

  public int getClockMapOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, java.lang.Integer> map =
        internalGetClockMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskId_ != 0L) {
      output.writeInt64(1, taskId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetClockMap(),
        ClockMapDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, taskId_);
    }
    for (java.util.Map.Entry<java.lang.Long, java.lang.Integer> entry
         : internalGetClockMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, java.lang.Integer>
      clockMap__ = ClockMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, clockMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tencent.client.master.protos.GetClockMapResp)) {
      return super.equals(obj);
    }
    com.tencent.client.master.protos.GetClockMapResp other = (com.tencent.client.master.protos.GetClockMapResp) obj;

    boolean result = true;
    result = result && (getTaskId()
        == other.getTaskId());
    result = result && internalGetClockMap().equals(
        other.internalGetClockMap());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTaskId());
    if (!internalGetClockMap().getMap().isEmpty()) {
      hash = (37 * hash) + CLOCKMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetClockMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.master.protos.GetClockMapResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tencent.client.master.protos.GetClockMapResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientMaster.GetClockMapResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientMaster.GetClockMapResp)
      com.tencent.client.master.protos.GetClockMapRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_GetClockMapResp_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetClockMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableClockMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_GetClockMapResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.client.master.protos.GetClockMapResp.class, com.tencent.client.master.protos.GetClockMapResp.Builder.class);
    }

    // Construct using com.tencent.client.master.protos.GetClockMapResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = 0L;

      internalGetMutableClockMap().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_GetClockMapResp_descriptor;
    }

    public com.tencent.client.master.protos.GetClockMapResp getDefaultInstanceForType() {
      return com.tencent.client.master.protos.GetClockMapResp.getDefaultInstance();
    }

    public com.tencent.client.master.protos.GetClockMapResp build() {
      com.tencent.client.master.protos.GetClockMapResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tencent.client.master.protos.GetClockMapResp buildPartial() {
      com.tencent.client.master.protos.GetClockMapResp result = new com.tencent.client.master.protos.GetClockMapResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      result.clockMap_ = internalGetClockMap();
      result.clockMap_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tencent.client.master.protos.GetClockMapResp) {
        return mergeFrom((com.tencent.client.master.protos.GetClockMapResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tencent.client.master.protos.GetClockMapResp other) {
      if (other == com.tencent.client.master.protos.GetClockMapResp.getDefaultInstance()) return this;
      if (other.getTaskId() != 0L) {
        setTaskId(other.getTaskId());
      }
      internalGetMutableClockMap().mergeFrom(
          other.internalGetClockMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tencent.client.master.protos.GetClockMapResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tencent.client.master.protos.GetClockMapResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long taskId_ ;
    /**
     * <code>int64 taskId = 1;</code>
     */
    public long getTaskId() {
      return taskId_;
    }
    /**
     * <code>int64 taskId = 1;</code>
     */
    public Builder setTaskId(long value) {
      
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.Integer> clockMap_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Integer>
    internalGetClockMap() {
      if (clockMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ClockMapDefaultEntryHolder.defaultEntry);
      }
      return clockMap_;
    }
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Integer>
    internalGetMutableClockMap() {
      onChanged();;
      if (clockMap_ == null) {
        clockMap_ = com.google.protobuf.MapField.newMapField(
            ClockMapDefaultEntryHolder.defaultEntry);
      }
      if (!clockMap_.isMutable()) {
        clockMap_ = clockMap_.copy();
      }
      return clockMap_;
    }

    public int getClockMapCount() {
      return internalGetClockMap().getMap().size();
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */

    public boolean containsClockMap(
        long key) {
      
      return internalGetClockMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getClockMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Integer> getClockMap() {
      return getClockMapMap();
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.Integer> getClockMapMap() {
      return internalGetClockMap().getMap();
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */

    public int getClockMapOrDefault(
        long key,
        int defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.Integer> map =
          internalGetClockMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */

    public int getClockMapOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.Integer> map =
          internalGetClockMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearClockMap() {
      internalGetMutableClockMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */

    public Builder removeClockMap(
        long key) {
      
      internalGetMutableClockMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Integer>
    getMutableClockMap() {
      return internalGetMutableClockMap().getMutableMap();
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */
    public Builder putClockMap(
        long key,
        int value) {
      
      
      internalGetMutableClockMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int64, int32&gt; clockMap = 2;</code>
     */

    public Builder putAllClockMap(
        java.util.Map<java.lang.Long, java.lang.Integer> values) {
      internalGetMutableClockMap().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientMaster.GetClockMapResp)
  }

  // @@protoc_insertion_point(class_scope:ClientMaster.GetClockMapResp)
  private static final com.tencent.client.master.protos.GetClockMapResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tencent.client.master.protos.GetClockMapResp();
  }

  public static com.tencent.client.master.protos.GetClockMapResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetClockMapResp>
      PARSER = new com.google.protobuf.AbstractParser<GetClockMapResp>() {
    public GetClockMapResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetClockMapResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetClockMapResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetClockMapResp> getParserForType() {
    return PARSER;
  }

  public com.tencent.client.master.protos.GetClockMapResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

