// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface GetClockMapReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.GetClockMapReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 taskId = 1;</code>
   */
  long getTaskId();
}
