// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface HeartBeatRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.HeartBeatResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientMaster.Command cmd = 3;</code>
   */
  int getCmdValue();
  /**
   * <code>.ClientMaster.Command cmd = 3;</code>
   */
  com.tencent.client.master.protos.Command getCmd();
}
