// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

/**
 * Protobuf type {@code ClientMaster.RegisterResp}
 */
public  final class RegisterResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientMaster.RegisterResp)
    RegisterRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterResp.newBuilder() to construct.
  private RegisterResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterResp() {
    ret_ = 0;
    workId_ = 0L;
    isChief_ = false;
    numTask_ = 0;
    asyncModel_ = 0;
    msg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            ret_ = rawValue;
            break;
          }
          case 16: {

            workId_ = input.readInt64();
            break;
          }
          case 24: {

            isChief_ = input.readBool();
            break;
          }
          case 32: {

            numTask_ = input.readInt32();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            asyncModel_ = rawValue;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 450: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              conf_ = com.google.protobuf.MapField.newMapField(
                  ConfDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            conf__ = input.readMessage(
                ConfDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            conf_.getMutableMap().put(
                conf__.getKey(), conf__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_RegisterResp_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 56:
        return internalGetConf();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_RegisterResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tencent.client.master.protos.RegisterResp.class, com.tencent.client.master.protos.RegisterResp.Builder.class);
  }

  private int bitField0_;
  public static final int RET_FIELD_NUMBER = 1;
  private int ret_;
  /**
   * <code>.Status ret = 1;</code>
   */
  public int getRetValue() {
    return ret_;
  }
  /**
   * <code>.Status ret = 1;</code>
   */
  public com.tencent.client.common.protos.Status getRet() {
    com.tencent.client.common.protos.Status result = com.tencent.client.common.protos.Status.valueOf(ret_);
    return result == null ? com.tencent.client.common.protos.Status.UNRECOGNIZED : result;
  }

  public static final int WORKID_FIELD_NUMBER = 2;
  private long workId_;
  /**
   * <code>int64 workId = 2;</code>
   */
  public long getWorkId() {
    return workId_;
  }

  public static final int ISCHIEF_FIELD_NUMBER = 3;
  private boolean isChief_;
  /**
   * <code>bool isChief = 3;</code>
   */
  public boolean getIsChief() {
    return isChief_;
  }

  public static final int NUMTASK_FIELD_NUMBER = 4;
  private int numTask_;
  /**
   * <code>int32 numTask = 4;</code>
   */
  public int getNumTask() {
    return numTask_;
  }

  public static final int ASYNCMODEL_FIELD_NUMBER = 5;
  private int asyncModel_;
  /**
   * <code>.AsyncModel asyncModel = 5;</code>
   */
  public int getAsyncModelValue() {
    return asyncModel_;
  }
  /**
   * <code>.AsyncModel asyncModel = 5;</code>
   */
  public com.tencent.client.common.protos.AsyncModel getAsyncModel() {
    com.tencent.client.common.protos.AsyncModel result = com.tencent.client.common.protos.AsyncModel.valueOf(asyncModel_);
    return result == null ? com.tencent.client.common.protos.AsyncModel.UNRECOGNIZED : result;
  }

  public static final int CONF_FIELD_NUMBER = 56;
  private static final class ConfDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_RegisterResp_ConfEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> conf_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetConf() {
    if (conf_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ConfDefaultEntryHolder.defaultEntry);
    }
    return conf_;
  }

  public int getConfCount() {
    return internalGetConf().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; conf = 56;</code>
   */

  public boolean containsConf(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetConf().getMap().containsKey(key);
  }
  /**
   * Use {@link #getConfMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getConf() {
    return getConfMap();
  }
  /**
   * <code>map&lt;string, string&gt; conf = 56;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getConfMap() {
    return internalGetConf().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; conf = 56;</code>
   */

  public java.lang.String getConfOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetConf().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; conf = 56;</code>
   */

  public java.lang.String getConfOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetConf().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int MSG_FIELD_NUMBER = 6;
  private volatile java.lang.Object msg_;
  /**
   * <code>string msg = 6;</code>
   */
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ret_ != com.tencent.client.common.protos.Status.OK.getNumber()) {
      output.writeEnum(1, ret_);
    }
    if (workId_ != 0L) {
      output.writeInt64(2, workId_);
    }
    if (isChief_ != false) {
      output.writeBool(3, isChief_);
    }
    if (numTask_ != 0) {
      output.writeInt32(4, numTask_);
    }
    if (asyncModel_ != com.tencent.client.common.protos.AsyncModel.BSP.getNumber()) {
      output.writeEnum(5, asyncModel_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msg_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetConf(),
        ConfDefaultEntryHolder.defaultEntry,
        56);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ret_ != com.tencent.client.common.protos.Status.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ret_);
    }
    if (workId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, workId_);
    }
    if (isChief_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isChief_);
    }
    if (numTask_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, numTask_);
    }
    if (asyncModel_ != com.tencent.client.common.protos.AsyncModel.BSP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, asyncModel_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msg_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetConf().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      conf__ = ConfDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(56, conf__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tencent.client.master.protos.RegisterResp)) {
      return super.equals(obj);
    }
    com.tencent.client.master.protos.RegisterResp other = (com.tencent.client.master.protos.RegisterResp) obj;

    boolean result = true;
    result = result && ret_ == other.ret_;
    result = result && (getWorkId()
        == other.getWorkId());
    result = result && (getIsChief()
        == other.getIsChief());
    result = result && (getNumTask()
        == other.getNumTask());
    result = result && asyncModel_ == other.asyncModel_;
    result = result && internalGetConf().equals(
        other.internalGetConf());
    result = result && getMsg()
        .equals(other.getMsg());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RET_FIELD_NUMBER;
    hash = (53 * hash) + ret_;
    hash = (37 * hash) + WORKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkId());
    hash = (37 * hash) + ISCHIEF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsChief());
    hash = (37 * hash) + NUMTASK_FIELD_NUMBER;
    hash = (53 * hash) + getNumTask();
    hash = (37 * hash) + ASYNCMODEL_FIELD_NUMBER;
    hash = (53 * hash) + asyncModel_;
    if (!internalGetConf().getMap().isEmpty()) {
      hash = (37 * hash) + CONF_FIELD_NUMBER;
      hash = (53 * hash) + internalGetConf().hashCode();
    }
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.master.protos.RegisterResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tencent.client.master.protos.RegisterResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.master.protos.RegisterResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tencent.client.master.protos.RegisterResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientMaster.RegisterResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientMaster.RegisterResp)
      com.tencent.client.master.protos.RegisterRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_RegisterResp_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 56:
          return internalGetConf();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 56:
          return internalGetMutableConf();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_RegisterResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.client.master.protos.RegisterResp.class, com.tencent.client.master.protos.RegisterResp.Builder.class);
    }

    // Construct using com.tencent.client.master.protos.RegisterResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ret_ = 0;

      workId_ = 0L;

      isChief_ = false;

      numTask_ = 0;

      asyncModel_ = 0;

      internalGetMutableConf().clear();
      msg_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tencent.client.master.protos.ClientMasterProto.internal_static_ClientMaster_RegisterResp_descriptor;
    }

    public com.tencent.client.master.protos.RegisterResp getDefaultInstanceForType() {
      return com.tencent.client.master.protos.RegisterResp.getDefaultInstance();
    }

    public com.tencent.client.master.protos.RegisterResp build() {
      com.tencent.client.master.protos.RegisterResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tencent.client.master.protos.RegisterResp buildPartial() {
      com.tencent.client.master.protos.RegisterResp result = new com.tencent.client.master.protos.RegisterResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.ret_ = ret_;
      result.workId_ = workId_;
      result.isChief_ = isChief_;
      result.numTask_ = numTask_;
      result.asyncModel_ = asyncModel_;
      result.conf_ = internalGetConf();
      result.conf_.makeImmutable();
      result.msg_ = msg_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tencent.client.master.protos.RegisterResp) {
        return mergeFrom((com.tencent.client.master.protos.RegisterResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tencent.client.master.protos.RegisterResp other) {
      if (other == com.tencent.client.master.protos.RegisterResp.getDefaultInstance()) return this;
      if (other.ret_ != 0) {
        setRetValue(other.getRetValue());
      }
      if (other.getWorkId() != 0L) {
        setWorkId(other.getWorkId());
      }
      if (other.getIsChief() != false) {
        setIsChief(other.getIsChief());
      }
      if (other.getNumTask() != 0) {
        setNumTask(other.getNumTask());
      }
      if (other.asyncModel_ != 0) {
        setAsyncModelValue(other.getAsyncModelValue());
      }
      internalGetMutableConf().mergeFrom(
          other.internalGetConf());
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tencent.client.master.protos.RegisterResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tencent.client.master.protos.RegisterResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ret_ = 0;
    /**
     * <code>.Status ret = 1;</code>
     */
    public int getRetValue() {
      return ret_;
    }
    /**
     * <code>.Status ret = 1;</code>
     */
    public Builder setRetValue(int value) {
      ret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Status ret = 1;</code>
     */
    public com.tencent.client.common.protos.Status getRet() {
      com.tencent.client.common.protos.Status result = com.tencent.client.common.protos.Status.valueOf(ret_);
      return result == null ? com.tencent.client.common.protos.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status ret = 1;</code>
     */
    public Builder setRet(com.tencent.client.common.protos.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ret_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Status ret = 1;</code>
     */
    public Builder clearRet() {
      
      ret_ = 0;
      onChanged();
      return this;
    }

    private long workId_ ;
    /**
     * <code>int64 workId = 2;</code>
     */
    public long getWorkId() {
      return workId_;
    }
    /**
     * <code>int64 workId = 2;</code>
     */
    public Builder setWorkId(long value) {
      
      workId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 workId = 2;</code>
     */
    public Builder clearWorkId() {
      
      workId_ = 0L;
      onChanged();
      return this;
    }

    private boolean isChief_ ;
    /**
     * <code>bool isChief = 3;</code>
     */
    public boolean getIsChief() {
      return isChief_;
    }
    /**
     * <code>bool isChief = 3;</code>
     */
    public Builder setIsChief(boolean value) {
      
      isChief_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isChief = 3;</code>
     */
    public Builder clearIsChief() {
      
      isChief_ = false;
      onChanged();
      return this;
    }

    private int numTask_ ;
    /**
     * <code>int32 numTask = 4;</code>
     */
    public int getNumTask() {
      return numTask_;
    }
    /**
     * <code>int32 numTask = 4;</code>
     */
    public Builder setNumTask(int value) {
      
      numTask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numTask = 4;</code>
     */
    public Builder clearNumTask() {
      
      numTask_ = 0;
      onChanged();
      return this;
    }

    private int asyncModel_ = 0;
    /**
     * <code>.AsyncModel asyncModel = 5;</code>
     */
    public int getAsyncModelValue() {
      return asyncModel_;
    }
    /**
     * <code>.AsyncModel asyncModel = 5;</code>
     */
    public Builder setAsyncModelValue(int value) {
      asyncModel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.AsyncModel asyncModel = 5;</code>
     */
    public com.tencent.client.common.protos.AsyncModel getAsyncModel() {
      com.tencent.client.common.protos.AsyncModel result = com.tencent.client.common.protos.AsyncModel.valueOf(asyncModel_);
      return result == null ? com.tencent.client.common.protos.AsyncModel.UNRECOGNIZED : result;
    }
    /**
     * <code>.AsyncModel asyncModel = 5;</code>
     */
    public Builder setAsyncModel(com.tencent.client.common.protos.AsyncModel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      asyncModel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.AsyncModel asyncModel = 5;</code>
     */
    public Builder clearAsyncModel() {
      
      asyncModel_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> conf_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetConf() {
      if (conf_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ConfDefaultEntryHolder.defaultEntry);
      }
      return conf_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableConf() {
      onChanged();;
      if (conf_ == null) {
        conf_ = com.google.protobuf.MapField.newMapField(
            ConfDefaultEntryHolder.defaultEntry);
      }
      if (!conf_.isMutable()) {
        conf_ = conf_.copy();
      }
      return conf_;
    }

    public int getConfCount() {
      return internalGetConf().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */

    public boolean containsConf(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetConf().getMap().containsKey(key);
    }
    /**
     * Use {@link #getConfMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getConf() {
      return getConfMap();
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getConfMap() {
      return internalGetConf().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */

    public java.lang.String getConfOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetConf().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */

    public java.lang.String getConfOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetConf().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearConf() {
      internalGetMutableConf().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */

    public Builder removeConf(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableConf().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableConf() {
      return internalGetMutableConf().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */
    public Builder putConf(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableConf().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; conf = 56;</code>
     */

    public Builder putAllConf(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableConf().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>string msg = 6;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 6;</code>
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 6;</code>
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 6;</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientMaster.RegisterResp)
  }

  // @@protoc_insertion_point(class_scope:ClientMaster.RegisterResp)
  private static final com.tencent.client.master.protos.RegisterResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tencent.client.master.protos.RegisterResp();
  }

  public static com.tencent.client.master.protos.RegisterResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterResp>
      PARSER = new com.google.protobuf.AbstractParser<RegisterResp>() {
    public RegisterResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterResp> getParserForType() {
    return PARSER;
  }

  public com.tencent.client.master.protos.RegisterResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

