// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface RegisterTaskRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.RegisterTaskResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 taskId = 2;</code>
   */
  long getTaskId();

  /**
   * <code>int32 numTask = 4;</code>
   */
  int getNumTask();

  /**
   * <code>map&lt;int64, int32&gt; clock = 3;</code>
   */
  int getClockCount();
  /**
   * <code>map&lt;int64, int32&gt; clock = 3;</code>
   */
  boolean containsClock(
      long key);
  /**
   * Use {@link #getClockMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Integer>
  getClock();
  /**
   * <code>map&lt;int64, int32&gt; clock = 3;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Integer>
  getClockMap();
  /**
   * <code>map&lt;int64, int32&gt; clock = 3;</code>
   */

  int getClockOrDefault(
      long key,
      int defaultValue);
  /**
   * <code>map&lt;int64, int32&gt; clock = 3;</code>
   */

  int getClockOrThrow(
      long key);
}
