// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface RegisterTaskReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.RegisterTaskReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 workId = 2;</code>
   */
  long getWorkId();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
