// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_master.proto

package com.tencent.client.master.protos;

public interface SetAngelLocationReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.SetAngelLocationReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 workId = 1;</code>
   */
  long getWorkId();

  /**
   * <code>string host = 2;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 post = 3;</code>
   */
  int getPost();
}
