// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_worker.proto

package com.tencent.client.worker.protos;

/**
 * Protobuf type {@code ClientMaster.RPCEmbedding}
 */
public  final class RPCEmbedding extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientMaster.RPCEmbedding)
    RPCEmbeddingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RPCEmbedding.newBuilder() to construct.
  private RPCEmbedding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RPCEmbedding() {
    pid_ = 0;
    name_ = "";
    numFeats_ = 0L;
    embeddingSize_ = 0;
    dtype_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RPCEmbedding(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            pid_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            numFeats_ = input.readInt64();
            break;
          }
          case 32: {

            embeddingSize_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dtype_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              initializerParams_ = com.google.protobuf.MapField.newMapField(
                  InitializerParamsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            initializerParams__ = input.readMessage(
                InitializerParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            initializerParams_.getMutableMap().put(
                initializerParams__.getKey(), initializerParams__.getValue());
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              updaterParams_ = com.google.protobuf.MapField.newMapField(
                  UpdaterParamsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000040;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            updaterParams__ = input.readMessage(
                UpdaterParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            updaterParams_.getMutableMap().put(
                updaterParams__.getKey(), updaterParams__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetInitializerParams();
      case 7:
        return internalGetUpdaterParams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tencent.client.worker.protos.RPCEmbedding.class, com.tencent.client.worker.protos.RPCEmbedding.Builder.class);
  }

  private int bitField0_;
  public static final int PID_FIELD_NUMBER = 1;
  private int pid_;
  /**
   * <code>int32 pid = 1;</code>
   */
  public int getPid() {
    return pid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMFEATS_FIELD_NUMBER = 3;
  private long numFeats_;
  /**
   * <code>int64 numFeats = 3;</code>
   */
  public long getNumFeats() {
    return numFeats_;
  }

  public static final int EMBEDDINGSIZE_FIELD_NUMBER = 4;
  private int embeddingSize_;
  /**
   * <code>int32 embeddingSize = 4;</code>
   */
  public int getEmbeddingSize() {
    return embeddingSize_;
  }

  public static final int DTYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object dtype_;
  /**
   * <code>string dtype = 5;</code>
   */
  public java.lang.String getDtype() {
    java.lang.Object ref = dtype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dtype_ = s;
      return s;
    }
  }
  /**
   * <code>string dtype = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDtypeBytes() {
    java.lang.Object ref = dtype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dtype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIALIZERPARAMS_FIELD_NUMBER = 6;
  private static final class InitializerParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_InitializerParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> initializerParams_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetInitializerParams() {
    if (initializerParams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InitializerParamsDefaultEntryHolder.defaultEntry);
    }
    return initializerParams_;
  }

  public int getInitializerParamsCount() {
    return internalGetInitializerParams().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 6;</code>
   */

  public boolean containsInitializerParams(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetInitializerParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInitializerParamsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getInitializerParams() {
    return getInitializerParamsMap();
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getInitializerParamsMap() {
    return internalGetInitializerParams().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 6;</code>
   */

  public java.lang.String getInitializerParamsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInitializerParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 6;</code>
   */

  public java.lang.String getInitializerParamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInitializerParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int UPDATERPARAMS_FIELD_NUMBER = 7;
  private static final class UpdaterParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_UpdaterParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> updaterParams_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetUpdaterParams() {
    if (updaterParams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UpdaterParamsDefaultEntryHolder.defaultEntry);
    }
    return updaterParams_;
  }

  public int getUpdaterParamsCount() {
    return internalGetUpdaterParams().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; updaterParams = 7;</code>
   */

  public boolean containsUpdaterParams(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetUpdaterParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUpdaterParamsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getUpdaterParams() {
    return getUpdaterParamsMap();
  }
  /**
   * <code>map&lt;string, string&gt; updaterParams = 7;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getUpdaterParamsMap() {
    return internalGetUpdaterParams().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; updaterParams = 7;</code>
   */

  public java.lang.String getUpdaterParamsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetUpdaterParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; updaterParams = 7;</code>
   */

  public java.lang.String getUpdaterParamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetUpdaterParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pid_ != 0) {
      output.writeInt32(1, pid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (numFeats_ != 0L) {
      output.writeInt64(3, numFeats_);
    }
    if (embeddingSize_ != 0) {
      output.writeInt32(4, embeddingSize_);
    }
    if (!getDtypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dtype_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetInitializerParams(),
        InitializerParamsDefaultEntryHolder.defaultEntry,
        6);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetUpdaterParams(),
        UpdaterParamsDefaultEntryHolder.defaultEntry,
        7);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (numFeats_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, numFeats_);
    }
    if (embeddingSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, embeddingSize_);
    }
    if (!getDtypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dtype_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetInitializerParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      initializerParams__ = InitializerParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, initializerParams__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetUpdaterParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      updaterParams__ = UpdaterParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, updaterParams__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tencent.client.worker.protos.RPCEmbedding)) {
      return super.equals(obj);
    }
    com.tencent.client.worker.protos.RPCEmbedding other = (com.tencent.client.worker.protos.RPCEmbedding) obj;

    boolean result = true;
    result = result && (getPid()
        == other.getPid());
    result = result && getName()
        .equals(other.getName());
    result = result && (getNumFeats()
        == other.getNumFeats());
    result = result && (getEmbeddingSize()
        == other.getEmbeddingSize());
    result = result && getDtype()
        .equals(other.getDtype());
    result = result && internalGetInitializerParams().equals(
        other.internalGetInitializerParams());
    result = result && internalGetUpdaterParams().equals(
        other.internalGetUpdaterParams());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PID_FIELD_NUMBER;
    hash = (53 * hash) + getPid();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + NUMFEATS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumFeats());
    hash = (37 * hash) + EMBEDDINGSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getEmbeddingSize();
    hash = (37 * hash) + DTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDtype().hashCode();
    if (!internalGetInitializerParams().getMap().isEmpty()) {
      hash = (37 * hash) + INITIALIZERPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInitializerParams().hashCode();
    }
    if (!internalGetUpdaterParams().getMap().isEmpty()) {
      hash = (37 * hash) + UPDATERPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUpdaterParams().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.worker.protos.RPCEmbedding parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tencent.client.worker.protos.RPCEmbedding prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientMaster.RPCEmbedding}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientMaster.RPCEmbedding)
      com.tencent.client.worker.protos.RPCEmbeddingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetInitializerParams();
        case 7:
          return internalGetUpdaterParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableInitializerParams();
        case 7:
          return internalGetMutableUpdaterParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.client.worker.protos.RPCEmbedding.class, com.tencent.client.worker.protos.RPCEmbedding.Builder.class);
    }

    // Construct using com.tencent.client.worker.protos.RPCEmbedding.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      pid_ = 0;

      name_ = "";

      numFeats_ = 0L;

      embeddingSize_ = 0;

      dtype_ = "";

      internalGetMutableInitializerParams().clear();
      internalGetMutableUpdaterParams().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCEmbedding_descriptor;
    }

    public com.tencent.client.worker.protos.RPCEmbedding getDefaultInstanceForType() {
      return com.tencent.client.worker.protos.RPCEmbedding.getDefaultInstance();
    }

    public com.tencent.client.worker.protos.RPCEmbedding build() {
      com.tencent.client.worker.protos.RPCEmbedding result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tencent.client.worker.protos.RPCEmbedding buildPartial() {
      com.tencent.client.worker.protos.RPCEmbedding result = new com.tencent.client.worker.protos.RPCEmbedding(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.pid_ = pid_;
      result.name_ = name_;
      result.numFeats_ = numFeats_;
      result.embeddingSize_ = embeddingSize_;
      result.dtype_ = dtype_;
      result.initializerParams_ = internalGetInitializerParams();
      result.initializerParams_.makeImmutable();
      result.updaterParams_ = internalGetUpdaterParams();
      result.updaterParams_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tencent.client.worker.protos.RPCEmbedding) {
        return mergeFrom((com.tencent.client.worker.protos.RPCEmbedding)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tencent.client.worker.protos.RPCEmbedding other) {
      if (other == com.tencent.client.worker.protos.RPCEmbedding.getDefaultInstance()) return this;
      if (other.getPid() != 0) {
        setPid(other.getPid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getNumFeats() != 0L) {
        setNumFeats(other.getNumFeats());
      }
      if (other.getEmbeddingSize() != 0) {
        setEmbeddingSize(other.getEmbeddingSize());
      }
      if (!other.getDtype().isEmpty()) {
        dtype_ = other.dtype_;
        onChanged();
      }
      internalGetMutableInitializerParams().mergeFrom(
          other.internalGetInitializerParams());
      internalGetMutableUpdaterParams().mergeFrom(
          other.internalGetUpdaterParams());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tencent.client.worker.protos.RPCEmbedding parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tencent.client.worker.protos.RPCEmbedding) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int pid_ ;
    /**
     * <code>int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }
    /**
     * <code>int32 pid = 1;</code>
     */
    public Builder setPid(int value) {
      
      pid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pid = 1;</code>
     */
    public Builder clearPid() {
      
      pid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long numFeats_ ;
    /**
     * <code>int64 numFeats = 3;</code>
     */
    public long getNumFeats() {
      return numFeats_;
    }
    /**
     * <code>int64 numFeats = 3;</code>
     */
    public Builder setNumFeats(long value) {
      
      numFeats_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 numFeats = 3;</code>
     */
    public Builder clearNumFeats() {
      
      numFeats_ = 0L;
      onChanged();
      return this;
    }

    private int embeddingSize_ ;
    /**
     * <code>int32 embeddingSize = 4;</code>
     */
    public int getEmbeddingSize() {
      return embeddingSize_;
    }
    /**
     * <code>int32 embeddingSize = 4;</code>
     */
    public Builder setEmbeddingSize(int value) {
      
      embeddingSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 embeddingSize = 4;</code>
     */
    public Builder clearEmbeddingSize() {
      
      embeddingSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dtype_ = "";
    /**
     * <code>string dtype = 5;</code>
     */
    public java.lang.String getDtype() {
      java.lang.Object ref = dtype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dtype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDtypeBytes() {
      java.lang.Object ref = dtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public Builder setDtype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public Builder clearDtype() {
      
      dtype_ = getDefaultInstance().getDtype();
      onChanged();
      return this;
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public Builder setDtypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dtype_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> initializerParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetInitializerParams() {
      if (initializerParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InitializerParamsDefaultEntryHolder.defaultEntry);
      }
      return initializerParams_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableInitializerParams() {
      onChanged();;
      if (initializerParams_ == null) {
        initializerParams_ = com.google.protobuf.MapField.newMapField(
            InitializerParamsDefaultEntryHolder.defaultEntry);
      }
      if (!initializerParams_.isMutable()) {
        initializerParams_ = initializerParams_.copy();
      }
      return initializerParams_;
    }

    public int getInitializerParamsCount() {
      return internalGetInitializerParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */

    public boolean containsInitializerParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInitializerParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInitializerParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInitializerParams() {
      return getInitializerParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getInitializerParamsMap() {
      return internalGetInitializerParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */

    public java.lang.String getInitializerParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInitializerParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */

    public java.lang.String getInitializerParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInitializerParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearInitializerParams() {
      internalGetMutableInitializerParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */

    public Builder removeInitializerParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInitializerParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableInitializerParams() {
      return internalGetMutableInitializerParams().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */
    public Builder putInitializerParams(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInitializerParams().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 6;</code>
     */

    public Builder putAllInitializerParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableInitializerParams().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> updaterParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetUpdaterParams() {
      if (updaterParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UpdaterParamsDefaultEntryHolder.defaultEntry);
      }
      return updaterParams_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableUpdaterParams() {
      onChanged();;
      if (updaterParams_ == null) {
        updaterParams_ = com.google.protobuf.MapField.newMapField(
            UpdaterParamsDefaultEntryHolder.defaultEntry);
      }
      if (!updaterParams_.isMutable()) {
        updaterParams_ = updaterParams_.copy();
      }
      return updaterParams_;
    }

    public int getUpdaterParamsCount() {
      return internalGetUpdaterParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */

    public boolean containsUpdaterParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetUpdaterParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUpdaterParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getUpdaterParams() {
      return getUpdaterParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getUpdaterParamsMap() {
      return internalGetUpdaterParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */

    public java.lang.String getUpdaterParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetUpdaterParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */

    public java.lang.String getUpdaterParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetUpdaterParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearUpdaterParams() {
      internalGetMutableUpdaterParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */

    public Builder removeUpdaterParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableUpdaterParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableUpdaterParams() {
      return internalGetMutableUpdaterParams().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */
    public Builder putUpdaterParams(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableUpdaterParams().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; updaterParams = 7;</code>
     */

    public Builder putAllUpdaterParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableUpdaterParams().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientMaster.RPCEmbedding)
  }

  // @@protoc_insertion_point(class_scope:ClientMaster.RPCEmbedding)
  private static final com.tencent.client.worker.protos.RPCEmbedding DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tencent.client.worker.protos.RPCEmbedding();
  }

  public static com.tencent.client.worker.protos.RPCEmbedding getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPCEmbedding>
      PARSER = new com.google.protobuf.AbstractParser<RPCEmbedding>() {
    public RPCEmbedding parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RPCEmbedding(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RPCEmbedding> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPCEmbedding> getParserForType() {
    return PARSER;
  }

  public com.tencent.client.worker.protos.RPCEmbedding getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

