// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_worker.proto

package com.tencent.client.worker.protos;

/**
 * Protobuf type {@code ClientMaster.RPCTensor}
 */
public  final class RPCTensor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientMaster.RPCTensor)
    RPCTensorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RPCTensor.newBuilder() to construct.
  private RPCTensor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RPCTensor() {
    taskId_ = 0L;
    name_ = "";
    dim_ = 0;
    shape_ = java.util.Collections.emptyList();
    dtype_ = "";
    validIndexNum_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RPCTensor(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            taskId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            dim_ = input.readInt32();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              shape_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000008;
            }
            shape_.add(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              shape_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              shape_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dtype_ = s;
            break;
          }
          case 48: {

            validIndexNum_ = input.readInt64();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              initializerParams_ = com.google.protobuf.MapField.newMapField(
                  InitializerParamsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000040;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            initializerParams__ = input.readMessage(
                InitializerParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            initializerParams_.getMutableMap().put(
                initializerParams__.getKey(), initializerParams__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        shape_ = java.util.Collections.unmodifiableList(shape_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCTensor_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetInitializerParams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCTensor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tencent.client.worker.protos.RPCTensor.class, com.tencent.client.worker.protos.RPCTensor.Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private long taskId_;
  /**
   * <code>int64 taskId = 1;</code>
   */
  public long getTaskId() {
    return taskId_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIM_FIELD_NUMBER = 3;
  private int dim_;
  /**
   * <code>int32 dim = 3;</code>
   */
  public int getDim() {
    return dim_;
  }

  public static final int SHAPE_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Long> shape_;
  /**
   * <code>repeated int64 shape = 4;</code>
   */
  public java.util.List<java.lang.Long>
      getShapeList() {
    return shape_;
  }
  /**
   * <code>repeated int64 shape = 4;</code>
   */
  public int getShapeCount() {
    return shape_.size();
  }
  /**
   * <code>repeated int64 shape = 4;</code>
   */
  public long getShape(int index) {
    return shape_.get(index);
  }
  private int shapeMemoizedSerializedSize = -1;

  public static final int DTYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object dtype_;
  /**
   * <code>string dtype = 5;</code>
   */
  public java.lang.String getDtype() {
    java.lang.Object ref = dtype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dtype_ = s;
      return s;
    }
  }
  /**
   * <code>string dtype = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDtypeBytes() {
    java.lang.Object ref = dtype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dtype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALIDINDEXNUM_FIELD_NUMBER = 6;
  private long validIndexNum_;
  /**
   * <code>int64 validIndexNum = 6;</code>
   */
  public long getValidIndexNum() {
    return validIndexNum_;
  }

  public static final int INITIALIZERPARAMS_FIELD_NUMBER = 7;
  private static final class InitializerParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCTensor_InitializerParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> initializerParams_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetInitializerParams() {
    if (initializerParams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InitializerParamsDefaultEntryHolder.defaultEntry);
    }
    return initializerParams_;
  }

  public int getInitializerParamsCount() {
    return internalGetInitializerParams().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 7;</code>
   */

  public boolean containsInitializerParams(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetInitializerParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInitializerParamsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getInitializerParams() {
    return getInitializerParamsMap();
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 7;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getInitializerParamsMap() {
    return internalGetInitializerParams().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 7;</code>
   */

  public java.lang.String getInitializerParamsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInitializerParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; initializerParams = 7;</code>
   */

  public java.lang.String getInitializerParamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInitializerParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (taskId_ != 0L) {
      output.writeInt64(1, taskId_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (dim_ != 0) {
      output.writeInt32(3, dim_);
    }
    if (getShapeList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(shapeMemoizedSerializedSize);
    }
    for (int i = 0; i < shape_.size(); i++) {
      output.writeInt64NoTag(shape_.get(i));
    }
    if (!getDtypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dtype_);
    }
    if (validIndexNum_ != 0L) {
      output.writeInt64(6, validIndexNum_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetInitializerParams(),
        InitializerParamsDefaultEntryHolder.defaultEntry,
        7);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, taskId_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (dim_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, dim_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < shape_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(shape_.get(i));
      }
      size += dataSize;
      if (!getShapeList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      shapeMemoizedSerializedSize = dataSize;
    }
    if (!getDtypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dtype_);
    }
    if (validIndexNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, validIndexNum_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetInitializerParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      initializerParams__ = InitializerParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, initializerParams__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tencent.client.worker.protos.RPCTensor)) {
      return super.equals(obj);
    }
    com.tencent.client.worker.protos.RPCTensor other = (com.tencent.client.worker.protos.RPCTensor) obj;

    boolean result = true;
    result = result && (getTaskId()
        == other.getTaskId());
    result = result && getName()
        .equals(other.getName());
    result = result && (getDim()
        == other.getDim());
    result = result && getShapeList()
        .equals(other.getShapeList());
    result = result && getDtype()
        .equals(other.getDtype());
    result = result && (getValidIndexNum()
        == other.getValidIndexNum());
    result = result && internalGetInitializerParams().equals(
        other.internalGetInitializerParams());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTaskId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DIM_FIELD_NUMBER;
    hash = (53 * hash) + getDim();
    if (getShapeCount() > 0) {
      hash = (37 * hash) + SHAPE_FIELD_NUMBER;
      hash = (53 * hash) + getShapeList().hashCode();
    }
    hash = (37 * hash) + DTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDtype().hashCode();
    hash = (37 * hash) + VALIDINDEXNUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValidIndexNum());
    if (!internalGetInitializerParams().getMap().isEmpty()) {
      hash = (37 * hash) + INITIALIZERPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInitializerParams().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.client.worker.protos.RPCTensor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tencent.client.worker.protos.RPCTensor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientMaster.RPCTensor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientMaster.RPCTensor)
      com.tencent.client.worker.protos.RPCTensorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCTensor_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetInitializerParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableInitializerParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCTensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.client.worker.protos.RPCTensor.class, com.tencent.client.worker.protos.RPCTensor.Builder.class);
    }

    // Construct using com.tencent.client.worker.protos.RPCTensor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = 0L;

      name_ = "";

      dim_ = 0;

      shape_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      dtype_ = "";

      validIndexNum_ = 0L;

      internalGetMutableInitializerParams().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tencent.client.worker.protos.ClientWorkerProto.internal_static_ClientMaster_RPCTensor_descriptor;
    }

    public com.tencent.client.worker.protos.RPCTensor getDefaultInstanceForType() {
      return com.tencent.client.worker.protos.RPCTensor.getDefaultInstance();
    }

    public com.tencent.client.worker.protos.RPCTensor build() {
      com.tencent.client.worker.protos.RPCTensor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tencent.client.worker.protos.RPCTensor buildPartial() {
      com.tencent.client.worker.protos.RPCTensor result = new com.tencent.client.worker.protos.RPCTensor(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      result.name_ = name_;
      result.dim_ = dim_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        shape_ = java.util.Collections.unmodifiableList(shape_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.shape_ = shape_;
      result.dtype_ = dtype_;
      result.validIndexNum_ = validIndexNum_;
      result.initializerParams_ = internalGetInitializerParams();
      result.initializerParams_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tencent.client.worker.protos.RPCTensor) {
        return mergeFrom((com.tencent.client.worker.protos.RPCTensor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tencent.client.worker.protos.RPCTensor other) {
      if (other == com.tencent.client.worker.protos.RPCTensor.getDefaultInstance()) return this;
      if (other.getTaskId() != 0L) {
        setTaskId(other.getTaskId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getDim() != 0) {
        setDim(other.getDim());
      }
      if (!other.shape_.isEmpty()) {
        if (shape_.isEmpty()) {
          shape_ = other.shape_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureShapeIsMutable();
          shape_.addAll(other.shape_);
        }
        onChanged();
      }
      if (!other.getDtype().isEmpty()) {
        dtype_ = other.dtype_;
        onChanged();
      }
      if (other.getValidIndexNum() != 0L) {
        setValidIndexNum(other.getValidIndexNum());
      }
      internalGetMutableInitializerParams().mergeFrom(
          other.internalGetInitializerParams());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tencent.client.worker.protos.RPCTensor parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tencent.client.worker.protos.RPCTensor) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long taskId_ ;
    /**
     * <code>int64 taskId = 1;</code>
     */
    public long getTaskId() {
      return taskId_;
    }
    /**
     * <code>int64 taskId = 1;</code>
     */
    public Builder setTaskId(long value) {
      
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int dim_ ;
    /**
     * <code>int32 dim = 3;</code>
     */
    public int getDim() {
      return dim_;
    }
    /**
     * <code>int32 dim = 3;</code>
     */
    public Builder setDim(int value) {
      
      dim_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dim = 3;</code>
     */
    public Builder clearDim() {
      
      dim_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> shape_ = java.util.Collections.emptyList();
    private void ensureShapeIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        shape_ = new java.util.ArrayList<java.lang.Long>(shape_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public java.util.List<java.lang.Long>
        getShapeList() {
      return java.util.Collections.unmodifiableList(shape_);
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public int getShapeCount() {
      return shape_.size();
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public long getShape(int index) {
      return shape_.get(index);
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public Builder setShape(
        int index, long value) {
      ensureShapeIsMutable();
      shape_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public Builder addShape(long value) {
      ensureShapeIsMutable();
      shape_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public Builder addAllShape(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureShapeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, shape_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 shape = 4;</code>
     */
    public Builder clearShape() {
      shape_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private java.lang.Object dtype_ = "";
    /**
     * <code>string dtype = 5;</code>
     */
    public java.lang.String getDtype() {
      java.lang.Object ref = dtype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dtype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDtypeBytes() {
      java.lang.Object ref = dtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public Builder setDtype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public Builder clearDtype() {
      
      dtype_ = getDefaultInstance().getDtype();
      onChanged();
      return this;
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public Builder setDtypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dtype_ = value;
      onChanged();
      return this;
    }

    private long validIndexNum_ ;
    /**
     * <code>int64 validIndexNum = 6;</code>
     */
    public long getValidIndexNum() {
      return validIndexNum_;
    }
    /**
     * <code>int64 validIndexNum = 6;</code>
     */
    public Builder setValidIndexNum(long value) {
      
      validIndexNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 validIndexNum = 6;</code>
     */
    public Builder clearValidIndexNum() {
      
      validIndexNum_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> initializerParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetInitializerParams() {
      if (initializerParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InitializerParamsDefaultEntryHolder.defaultEntry);
      }
      return initializerParams_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableInitializerParams() {
      onChanged();;
      if (initializerParams_ == null) {
        initializerParams_ = com.google.protobuf.MapField.newMapField(
            InitializerParamsDefaultEntryHolder.defaultEntry);
      }
      if (!initializerParams_.isMutable()) {
        initializerParams_ = initializerParams_.copy();
      }
      return initializerParams_;
    }

    public int getInitializerParamsCount() {
      return internalGetInitializerParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */

    public boolean containsInitializerParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInitializerParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInitializerParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInitializerParams() {
      return getInitializerParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getInitializerParamsMap() {
      return internalGetInitializerParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */

    public java.lang.String getInitializerParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInitializerParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */

    public java.lang.String getInitializerParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInitializerParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearInitializerParams() {
      internalGetMutableInitializerParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */

    public Builder removeInitializerParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInitializerParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableInitializerParams() {
      return internalGetMutableInitializerParams().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */
    public Builder putInitializerParams(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInitializerParams().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; initializerParams = 7;</code>
     */

    public Builder putAllInitializerParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableInitializerParams().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientMaster.RPCTensor)
  }

  // @@protoc_insertion_point(class_scope:ClientMaster.RPCTensor)
  private static final com.tencent.client.worker.protos.RPCTensor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tencent.client.worker.protos.RPCTensor();
  }

  public static com.tencent.client.worker.protos.RPCTensor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPCTensor>
      PARSER = new com.google.protobuf.AbstractParser<RPCTensor>() {
    public RPCTensor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RPCTensor(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RPCTensor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPCTensor> getParserForType() {
    return PARSER;
  }

  public com.tencent.client.worker.protos.RPCTensor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

