// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_worker.proto

package com.tencent.client.worker.protos;

public interface SaveTensorLikeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.SaveTensorLike)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 taskId = 1;</code>
   */
  long getTaskId();

  /**
   * <code>int32 matId = 2;</code>
   */
  int getMatId();

  /**
   * <code>string path = 3;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 3;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string formatClassName = 4;</code>
   */
  java.lang.String getFormatClassName();
  /**
   * <code>string formatClassName = 4;</code>
   */
  com.google.protobuf.ByteString
      getFormatClassNameBytes();
}
