// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_worker.proto

package com.tencent.client.worker.protos;

public interface SyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.SyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pid = 1;</code>
   */
  int getPid();

  /**
   * <code>int64 clock = 2;</code>
   */
  long getClock();
}
