// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_worker.proto

package com.tencent.client.worker.protos;

public interface VoidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMaster.VoidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Status ret = 1;</code>
   */
  int getRetValue();
  /**
   * <code>.Status ret = 1;</code>
   */
  com.tencent.client.common.protos.Status getRet();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
